name: aura # Add this line with your app's name
description: A new Flutter project for sensing air quality.


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.2
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.0.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  fl_chart: ^0.68.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0