// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-t7d_eKevOOSWSoaevfP1fb_HRYMIgcc',
    appId: '1:217967984385:web:3937db7c291059d7c36500',
    messagingSenderId: '217967984385',
    projectId: 'aura-myosa',
    authDomain: 'aura-myosa.firebaseapp.com',
    storageBucket: 'aura-myosa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4vjcSDa3Jrzl8stsHNie-5GH_-Ql0Lyg',
    appId: '1:217967984385:android:1b14f0e7a39c2507c36500',
    messagingSenderId: '217967984385',
    projectId: 'aura-myosa',
    storageBucket: 'aura-myosa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFRo_hoaWtUBJaHDAhqb8UoIAQcbtuZsc',
    appId: '1:217967984385:ios:6dd4d41a10def762c36500',
    messagingSenderId: '217967984385',
    projectId: 'aura-myosa',
    storageBucket: 'aura-myosa.firebasestorage.app',
    iosBundleId: 'com.example.myosa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFRo_hoaWtUBJaHDAhqb8UoIAQcbtuZsc',
    appId: '1:217967984385:ios:6dd4d41a10def762c36500',
    messagingSenderId: '217967984385',
    projectId: 'aura-myosa',
    storageBucket: 'aura-myosa.firebasestorage.app',
    iosBundleId: 'com.example.myosa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-t7d_eKevOOSWSoaevfP1fb_HRYMIgcc',
    appId: '1:217967984385:web:362fdb1753134d49c36500',
    messagingSenderId: '217967984385',
    projectId: 'aura-myosa',
    authDomain: 'aura-myosa.firebaseapp.com',
    storageBucket: 'aura-myosa.firebasestorage.app',
  );

}